### PR TITLE
assign feedback

### PR DESCRIPTION
**Pull request by matthewlilley**

### CODE REVIEW

**Comment by matfish2** [comment]
Please explain the rational behind the PR.

**Comment by matthewlilley** [comment]
1. Feedback was not getting assigned when there was feedback, so the icon would not show.

2. Left padded string to separate class.

Label also needed moving inside the same div as the feedback and input, or the compensating css isn't effective.

**Comment by matfish2** [comment]
The label is positioned correctly. It should be wrapped with the outer wrapper but outside the inner field wrapper. This allows for horizontal form layout where the label and the field share portions of the grid.
Here is an example from bootstrap`s docs:

```html
<div class="form-group row">
  <label for="example-text-input" class="col-xs-2 col-form-label">Text</label>
  <div class="col-xs-10">
    <input class="form-control" type="text" value="Artisanal kale" id="example-text-input">
  </div>
</div>

```
Please undo this last commit and I will merge the request.

**Comment by matthewlilley** [comment]
Hey,

For the label, this is how the feedback is positioned when label is outside of the wrapping div.

http://prntscr.com/dacbxc

This bootstrap css has no effect.

```
.has-feedback label ~ .form-control-feedback {
    top: 25px;
}
```

**Comment by matthewlilley** [comment]
I'll look at this later tonight and see if I can solve this properly.

**Comment by matthewlilley** [comment]
When labels are disabled, it's fine and the feedback is positioned correctly. When labeled are enabled, the compensating css (shown above) does nothing.

What are your thoughts on this?

Here's a screenshot to show you what's happening. http://prnt.sc/daujvm

**Comment by matfish2** [comment]
Did you try to move the feedback icon one level up?
Anyway, the template is supposed to support both horizontal and vertical layout, so having the icon aligned for both options out of the box seems far-fetched.
I am not sure what you mean by "the compensating css does nothing". If you give the icon a relative position (which I don't see in your code) and move it around, it should align perfectly.

**Comment by matfish2** [comment]
Thanks for the PR. I've assigned the feedback icon myself. Will look into the positioning issue.

**Pull request closed without merging**
